"""empty message

Revision ID: 5f056fcf6d48
Revises: 
Create Date: 2020-03-10 21:33:57.230891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f056fcf6d48'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('c_goods_id', sa.Integer(), nullable=False),
    sa.Column('c_user_id', sa.Integer(), nullable=False),
    sa.Column('c_goods_num', sa.Integer(), nullable=True),
    sa.Column('is_select', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('o_user_id', sa.Integer(), nullable=False),
    sa.Column('o_price', sa.Float(), nullable=True),
    sa.Column('o_status', sa.Integer(), nullable=True),
    sa.Column('o_order_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_goods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('o_order_id', sa.Integer(), nullable=False),
    sa.Column('o_goods_num', sa.Integer(), nullable=True),
    sa.Column('o_goods_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_goods')
    op.drop_table('order')
    op.drop_table('cart')
    # ### end Alembic commands ###
